#ifndef WORLD_H
#define WORLD_H

#include <chunk.h>

#define WORLD_SIZE_X 32
#define WORLD_SIZE_Z 32

/** @brief Struct containing all the data needed to draw the entire world.
 */
typedef struct {
    chunk_t chunks[WORLD_SIZE_X][WORLD_SIZE_Z];
} world_t;

/**
 * @brief Fills the chunk array of the world with the chunks and their
 * position.
 * @param world Pointer to world structure to be initalized.
 */
void world_init(world_t* world);

/**
 * Builds the meshes of all the chunks contained in the world.
 * @param world Pointer to the world to the built.
 */
void world_build(world_t* world);

/** @brief Rebuilds a sigle chunk of the world. */
void world_build_chunk(world_t* world, int cx, int cz);

/**
 * @brief Rebuilds the mesh of a chunk and any neighbors whose visible
 * geometry changed because a border block was modified.
 * @param world Pointer to the world that will be modified
 * @param chunk_x Chunk grid X of the modified chunk.
 * @param chunk_z Chunk grid Z of the modified chunk.
 * @param local_x Block's local X within the chunk.
 * @param local_z Block's local Z within the chunk.
 */
void world_rebuild_after_change(world_t* world, int chunk_x, int chunk_z,
                                int local_x, int local_z);

/**
 * @brief Uses a world, a shader and a texture atlas to draw all the chunks
 * on screen.
 * @param world Pointer to the world to be drawn.
 * @param shader Pointer to shader program to be used.
 * @param atlas Pointer to atlas texture material to be used.
 */
void world_draw(world_t* world, const shader_t* shader, material_t* atlas,
                vec4 frustum[6]);

/**
 * @brief Frees all chunks in the world.
 * @param world Pointer to the world to be destroyed.
 */
void world_destroy(world_t* world);

/** @brief Checks if that position exists in the world
 * @param position Vec3 containing the position to check.
 */
bool world_valid_position(const vec3 position);

/**
 * @brief Fills world with half filled chunks with a surface of grass, 3
 * layers of dirt, 1 layer of sand, then stone.
 * @param world The world to be filled.
 */
void world_fill_superflat(world_t* world);

/**
 * @brief Fills world with chunks generated by a perlin noise algorithm.
 * @param world The world to be filled.
 * @param scale Scale of the perlin noise algorithm. A smaller value means
 * broader hills, and a higher means more jagged peaks.
 * @param sea_level Height of the sea level.
 * @param amplitude Amplitude of the perlin noise algorithm. How many
 * blocks of height variations is wanted.
 */
void world_fill_perlin(world_t* world, float scale, int sea_level,
                       int amplitude);

#endif // WORLD_H
