#include "game_config.h"

game_config_t game_config_default(void) {
    return (game_config_t) {.width                     = 800,
                            .height                    = 600,
                            .version                   = "v0.1.6",
                            .title                     = "da-cubec",
                            .cube_vertex_shader_path   = "src/shaders/cube.vert.glsl",
                            .cube_fragment_shader_path = "src/shaders/cube.frag.glsl",
                            .text_vertex_shader_path   = "src/shaders/text.vert.glsl",
                            .text_fragment_shader_path = "src/shaders/text.frag.glsl",
                            .debug_font_path           = "fonts/pix32.ttf",
                            .texture_atlas_path        = "img/atlas.png",
                            .sensitivity               = 0.05F,
                            .speed                     = 25.0F,
                            .fov                       = 70.0F,
                            .free_camera               = true,
                            .player_walk_speed         = 5.0F,
                            .player_sprint_speed       = 10.0F,
                            .player_jump_velocity      = 8.5F,
                            .gravity                   = 25.0F,
                            .player_width              = 0.5F,
                            .player_height             = 2.0F,
                            .player_eye_offset         = 1.5F,
                            .terminal_velocity         = 50.0F,
                            .max_reach                 = 6.0F,
                            .sky_color                 = {0.85F, 0.85F, 1.0F, 1.0F},
                            .render_distance           = 8,
                            .debug_font_size           = 28.0F};
}
